apiVersion: apps/v1
kind: Deployment
metadata:
  name: variaveis
spec:
  replicas: 10
  selector:
    matchLabels:
      app: variaveis
  template:
    metadata:
      labels:
        app: variaveis
    spec:
      containers:
      - name: variaveis
        image: lucasbref82/variaveis-ambiente:v3
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: variaveis
spec:
  selector:
    app: variaveis
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30000
  type: NodePort
