apiVersion: apps/v1
kind: Deployment
metadata:
  name: variaveis
spec:
  replicas: 10
  selector:
    matchLabels:
      app: variaveis
  template:
    metadata:
      labels:
        app: variaveis
    spec:
      containers:
      - name: variaveis

        image: lucasbref82/variaveis-ambiente:v7
        ports:
        - containerPort: 80
        envFrom:
          - configMapRef:
              name: config-variaveis
