apiVersion: apps/v1
kind: Deployment
metadata:
  name: variaveis
spec:
  replicas: 10
  selector:
    matchLabels:
      app: variaveis
  template:
    metadata:
      labels:
        app: variaveis
    spec:
      containers:
      - name: variaveis
        image: lucasbref82/variaveis-ambiente:v4
        ports:
        - containerPort: 80
        env:
          - name: APP_NAME
            valueFrom: 
              configMapKeyRef:
                name: config-variaveis
                key: APP_NAME
          - name: SERVER_PORT
            valueFrom: 
              configMapKeyRef:
                name: config-variaveis
                key: SERVER_PORT
          - name: LUCAS_NOME
            valueFrom: 
              configMapKeyRef:
                name: config-variaveis
                key: LUCAS_NOME
          - name: LUCAS_EMAIL
            valueFrom: 
              configMapKeyRef:
                name: config-variaveis
                key: LUCAS_EMAIL
          - name: LUCAS_IDADE
            valueFrom: 
              configMapKeyRef:
                name: config-variaveis
                key: LUCAS_IDADE
---
apiVersion: v1
kind: Service
metadata:
  name: variaveis
spec:
  selector:
    app: variaveis
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30000
  type: NodePort
